// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package http

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
)

// ActionRequest defines model for ActionRequest.
type ActionRequest struct {
	// Payload Dynamic payload depending on the action type.
	Payload interface{} `json:"payload"`

	// Type The type of action (e.g., RENDER_CONTENT, REQUEST_INPUT).
	Type string `json:"type"`
}

// NavigateRequest defines model for NavigateRequest.
type NavigateRequest struct {
	// Input The user input to drive the transition.
	Input *string `json:"input,omitempty"`
	State State   `json:"state"`
}

// RenderResponse defines model for RenderResponse.
type RenderResponse struct {
	Actions *[]ActionRequest `json:"actions,omitempty"`

	// Terminal True if the current node has no outgoing transitions.
	Terminal *bool `json:"terminal,omitempty"`
}

// State defines model for State.
type State struct {
	// CurrentNodeId The identifier of the active node.
	CurrentNodeId string `json:"current_node_id"`

	// History Trace of visited nodes.
	History *[]string `json:"history,omitempty"`

	// Memory Key-value store for session variables.
	Memory *map[string]interface{} `json:"memory,omitempty"`

	// Terminated Indicates if the execution has reached a sink state.
	Terminated *bool `json:"terminated,omitempty"`
}

// NavigateJSONRequestBody defines body for Navigate for application/json ContentType.
type NavigateJSONRequestBody = NavigateRequest

// RenderJSONRequestBody defines body for Render for application/json ContentType.
type RenderJSONRequestBody = State

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Introspect the full state machine graph
	// (GET /graph)
	GetGraph(w http.ResponseWriter, r *http.Request)
	// Transition to the next state based on input
	// (POST /navigate)
	Navigate(w http.ResponseWriter, r *http.Request)
	// Get the current view (actions) for a given state
	// (POST /render)
	Render(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Introspect the full state machine graph
// (GET /graph)
func (_ Unimplemented) GetGraph(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Transition to the next state based on input
// (POST /navigate)
func (_ Unimplemented) Navigate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the current view (actions) for a given state
// (POST /render)
func (_ Unimplemented) Render(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetGraph operation middleware
func (siw *ServerInterfaceWrapper) GetGraph(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGraph(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Navigate operation middleware
func (siw *ServerInterfaceWrapper) Navigate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Navigate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Render operation middleware
func (siw *ServerInterfaceWrapper) Render(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Render(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/graph", wrapper.GetGraph)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/navigate", wrapper.Navigate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/render", wrapper.Render)
	})

	return r
}
