// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ActionRequest defines model for ActionRequest.
type ActionRequest struct {
	// Payload Dynamic payload depending on the action type.
	Payload interface{} `json:"payload"`

	// Type The type of action (e.g., RENDER_CONTENT, REQUEST_INPUT).
	Type string `json:"type"`
}

// NavigateRequest defines model for NavigateRequest.
type NavigateRequest struct {
	// Input The user input or tool result.
	Input *NavigateRequest_Input `json:"input,omitempty"`
	State State                  `json:"state"`
}

// NavigateRequestInput0 defines model for .
type NavigateRequestInput0 = string

// NavigateRequest_Input The user input or tool result.
type NavigateRequest_Input struct {
	union json.RawMessage
}

// RenderResponse defines model for RenderResponse.
type RenderResponse struct {
	Actions *[]ActionRequest `json:"actions,omitempty"`

	// Terminal True if the current node has no outgoing transitions.
	Terminal *bool `json:"terminal,omitempty"`
}

// State defines model for State.
type State struct {
	// CurrentNodeId The identifier of the active node.
	CurrentNodeId string `json:"current_node_id"`

	// History Trace of visited nodes.
	History *[]string `json:"history,omitempty"`

	// Memory Key-value store for session variables.
	Memory *map[string]interface{} `json:"memory,omitempty"`

	// Terminated Indicates if the execution has reached a sink state.
	Terminated *bool `json:"terminated,omitempty"`
}

// ToolResult defines model for ToolResult.
type ToolResult struct {
	Error *string `json:"error,omitempty"`

	// Id Corresponds to the ToolCall ID.
	Id      string `json:"id"`
	IsError *bool  `json:"is_error,omitempty"`

	// Result The output of the tool execution.
	Result interface{} `json:"result"`
}

// NavigateJSONRequestBody defines body for Navigate for application/json ContentType.
type NavigateJSONRequestBody = NavigateRequest

// RenderJSONRequestBody defines body for Render for application/json ContentType.
type RenderJSONRequestBody = State

// AsNavigateRequestInput0 returns the union data inside the NavigateRequest_Input as a NavigateRequestInput0
func (t NavigateRequest_Input) AsNavigateRequestInput0() (NavigateRequestInput0, error) {
	var body NavigateRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNavigateRequestInput0 overwrites any union data inside the NavigateRequest_Input as the provided NavigateRequestInput0
func (t *NavigateRequest_Input) FromNavigateRequestInput0(v NavigateRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNavigateRequestInput0 performs a merge with any union data inside the NavigateRequest_Input, using the provided NavigateRequestInput0
func (t *NavigateRequest_Input) MergeNavigateRequestInput0(v NavigateRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsToolResult returns the union data inside the NavigateRequest_Input as a ToolResult
func (t NavigateRequest_Input) AsToolResult() (ToolResult, error) {
	var body ToolResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromToolResult overwrites any union data inside the NavigateRequest_Input as the provided ToolResult
func (t *NavigateRequest_Input) FromToolResult(v ToolResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeToolResult performs a merge with any union data inside the NavigateRequest_Input, using the provided ToolResult
func (t *NavigateRequest_Input) MergeToolResult(v ToolResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NavigateRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *NavigateRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Subscribe to server-sent events for graph changes
	// (GET /events)
	SubscribeEvents(w http.ResponseWriter, r *http.Request)
	// Introspect the full state machine graph
	// (GET /graph)
	GetGraph(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Server metadata and version information
	// (GET /info)
	GetInfo(w http.ResponseWriter, r *http.Request)
	// Transition to the next state based on input
	// (POST /navigate)
	Navigate(w http.ResponseWriter, r *http.Request)
	// Get the current view (actions) for a given state
	// (POST /render)
	Render(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Subscribe to server-sent events for graph changes
// (GET /events)
func (_ Unimplemented) SubscribeEvents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Introspect the full state machine graph
// (GET /graph)
func (_ Unimplemented) GetGraph(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Server metadata and version information
// (GET /info)
func (_ Unimplemented) GetInfo(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Transition to the next state based on input
// (POST /navigate)
func (_ Unimplemented) Navigate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the current view (actions) for a given state
// (POST /render)
func (_ Unimplemented) Render(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// SubscribeEvents operation middleware
func (siw *ServerInterfaceWrapper) SubscribeEvents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubscribeEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGraph operation middleware
func (siw *ServerInterfaceWrapper) GetGraph(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGraph(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInfo operation middleware
func (siw *ServerInterfaceWrapper) GetInfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Navigate operation middleware
func (siw *ServerInterfaceWrapper) Navigate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Navigate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Render operation middleware
func (siw *ServerInterfaceWrapper) Render(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Render(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events", wrapper.SubscribeEvents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/graph", wrapper.GetGraph)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/info", wrapper.GetInfo)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/navigate", wrapper.Navigate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/render", wrapper.Render)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xX32/bRgz+Vw63PbSAY3vtBhR+65qgNdalneM+tUVAS7R17elOvaPUGIH/94E82bFk",
	"Jd3WbU/5cSSP/L6PPOpWZ76svENHUc9udcwKLEF+fZ6R8W6BX2qMxP+ogq8wkEE5rmBrPeT8a44xC6Zi",
	"cz3T51sHpclUa6ByrNDlxm2Ud4oKVCCBFW0rHOuRdrW1sLKoZxRq3I00H5yGXRYoLsqv9xEe4XgzHqnF",
	"xeX5xeL6xZvL5cXlkv/+493F1fJ6fvn23fIxX5Ei6kjBuI3e7UY64JfaBMz17H06/Xiw8qtPmJHejfQl",
	"NGYDhPdiYFxV03CqdcSg5Fz5oMh7qwLG2hLn4x2+WevZ+9t+ZqNb/WPAtZ7pHyZ3xExaViZL7+1Coujd",
	"x91IRwISqB5yuhKjftHJdajqBbocwwJj5V3E06IT+Kl+wjJ+6/6ujg78aggBtvI3htI4sANAhhqVWYtq",
	"sjoEdKScz1EVEJXzyte08awsCuCikbyO+F55bxGc1H5S5tUeu2517TXXfM21yYfJNTk6MmuDgdW413SD",
	"ktyA4Ea6MJF82A6VCJloujHREOYSQoo4gHsSrA9giWUbG/JcUAD79qgq7qtR797fcHvWgK1RcWKo1j6o",
	"iDFyXzUQDHfkMZZ3wLV0EQ6AM3e5yYAw7lnDG8xqaVamLCBkBeYKVDTusxIN3sPXsVb7nAyp9qg1TjjF",
	"EHwYRHKI4Bc+BBF/HhV5qYKDvwBr1fx8kF0Tr/t3HGrhUvZpnSrJ1yQjIqElY+IA2cBw7AEziAUbGbf2",
	"pxc+fzsXno0jDKxYt1FfDRWpxoDWmqikL9TvkBXGobpwG/5hHHPGJxZjVCU4h2H8wTEYhjg93fEXqysM",
	"DQY90g2GmDKYjp+Mp4yJr9BBZfRMPx1Px0/1SFdAhbA1wWb/Gm1QYGMugWuY53qmr+oVF7XCi2QnAMus",
	"Ep8n06n0sXeETtwJbygFPYsUEMq7h07UcQNlJSXkQDBTAfnZ+uBSdb2XY9fvI0lCpbgKI8HKmlhgLiKO",
	"dVkCd+Zd0iypKMCcRfZMxQotmwBVobIC3Aaj+E/kX/ci8RLppRh8EwKoKsuNabybfIqc+DECh0nz0Pg4",
	"nQOdKXSKDMt7XVvb1pXj2jiJ3oNm7ij4WGFGokNxEampshVhQkEAKRAsPYjIq2TxnZB0BwinU8euWPzn",
	"wcVioBm7sKSuUCYqsKbBHhivTYOOm6cKfpUOJ/tmvq/iOZ//q/VCZa4PTXtc9HT803g6NAGhqrqWlMbB",
	"WUFUDTncE/6pzIJ/DmuJBNzG/fbrnipwuWozUAxvKOGgzIlr1z7BxccB0PeLoU7jGCP96vPt3wL8oY2p",
	"v3fuunO/XZO/i++/sjCeYHyJX1NnMoE/pxv7738D1uRp8WWrX4atCIMD2w5Cld7OLmPLw0a3f4Qd3lA7",
	"GFYQMVfCndzDrAVZW+/nLK21/xFjR5D9fzz1FvWhpqizDGNc1/zxwcZt8z3IXYL4+xl8idRZ3BuDX9Wj",
	"9uvhsbx4oDY87/aiEn8JGOXjqHvna5+BVefY3C0WdbB6pnnEzCYTy+eFjzS7rXygHS8e+0U2ySK0S9ga",
	"ZB/Tz6bPeJgNDhKx5oxO1sO2nFc+knq0QAu8+T8+ZDPhT7M/AwAA///m78CqVw8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
