version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/trellis
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: trellis
    ldflags:
      - -s -w -X github.com/aretw0/trellis.Version={{.Version}}

archives:
  - formats:
      - tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows
    format_overrides:
      - goos: windows
        formats:
          - zip

release:
  github:
    owner: aretw0
    name: trellis
  draft: true
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^refactor:"
      - "^style:"
      - "^Merge pull request"
      - "^Merge branch"
  groups:
    - title: Features
      regexp: "^.*feat((\\([\\w\\-\\.]+\\))?):"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix((\\([\\w\\-\\.]+\\))?):"
      order: 1
    - title: "Performance Improvements"
      regexp: "^.*perf((\\([\\w\\-\\.]+\\))?):"
      order: 2
    - title: "Others"
      order: 999

brews:
  - repository:
      owner: aretw0
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/aretw0/trellis"
    description: "Deterministic state machine engine for CLIs and automation."
    license: "AGPL-3.0"

scoops:
  - repository:
      owner: aretw0
      name: scoop-bucket
    homepage: "https://github.com/aretw0/trellis"
    description: "Deterministic state machine engine for CLIs and automation."
    license: "AGPL-3.0"

winget:
  - publisher: aretw0
    publisher_url: "https://github.com/aretw0"
    publisher_support_url: "https://github.com/aretw0/trellis/issues"
    package_identifier: "aretw0.trellis"
    name: "trellis"
    homepage: "https://github.com/aretw0/trellis"
    license: "AGPL-3.0"
    license_url: "https://github.com/aretw0/trellis/blob/main/LICENSE.txt"
    short_description: "Deterministic state machine engine for CLIs and automation."
    repository:
      owner: aretw0
      name: winget-pkgs
