// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ActionRequest defines model for ActionRequest.
type ActionRequest struct {
	// Payload Dynamic payload depending on the action type.
	Payload interface{} `json:"payload"`

	// Type The type of action (e.g., RENDER_CONTENT, REQUEST_INPUT).
	Type string `json:"type"`
}

// NavigateRequest defines model for NavigateRequest.
type NavigateRequest struct {
	// Input The user input or tool result.
	Input *NavigateRequest_Input `json:"input,omitempty"`
	State State                  `json:"state"`
}

// NavigateRequestInput0 defines model for .
type NavigateRequestInput0 = string

// NavigateRequest_Input The user input or tool result.
type NavigateRequest_Input struct {
	union json.RawMessage
}

// RenderResponse defines model for RenderResponse.
type RenderResponse struct {
	Actions *[]ActionRequest `json:"actions,omitempty"`
	State   *State           `json:"state,omitempty"`

	// Terminal True if the current node has no outgoing transitions.
	Terminal *bool `json:"terminal,omitempty"`
}

// State defines model for State.
type State struct {
	// Actions List of actions to be performed (e.g., render content).
	Actions *[]ActionRequest `json:"actions,omitempty"`

	// CurrentNodeId The identifier of the active node.
	CurrentNodeId string `json:"current_node_id"`

	// History Trace of visited nodes.
	History *[]string `json:"history,omitempty"`

	// Memory Key-value store for session variables.
	Memory    *map[string]interface{} `json:"memory,omitempty"`
	SessionId *string                 `json:"session_id,omitempty"`

	// Terminated Indicates if the execution has reached a sink state.
	Terminated *bool `json:"terminated,omitempty"`
}

// ToolResult defines model for ToolResult.
type ToolResult struct {
	Error *string `json:"error,omitempty"`

	// Id Corresponds to the ToolCall ID.
	Id      string `json:"id"`
	IsError *bool  `json:"is_error,omitempty"`

	// Result The output of the tool execution.
	Result interface{} `json:"result"`
}

// SubscribeEventsParams defines parameters for SubscribeEvents.
type SubscribeEventsParams struct {
	// SessionId Session ID to subscribe to for state updates
	SessionId *string `form:"session_id,omitempty" json:"session_id,omitempty"`

	// Watch Comma-separated list of fields to watch (e.g. "context,history")
	Watch *string `form:"watch,omitempty" json:"watch,omitempty"`
}

// SignalJSONBody defines parameters for Signal.
type SignalJSONBody struct {
	// Signal The name of the signal (e.g., "interrupt", "timeout")
	Signal string `json:"signal"`
	State  State  `json:"state"`
}

// NavigateJSONRequestBody defines body for Navigate for application/json ContentType.
type NavigateJSONRequestBody = NavigateRequest

// RenderJSONRequestBody defines body for Render for application/json ContentType.
type RenderJSONRequestBody = State

// SignalJSONRequestBody defines body for Signal for application/json ContentType.
type SignalJSONRequestBody SignalJSONBody

// AsNavigateRequestInput0 returns the union data inside the NavigateRequest_Input as a NavigateRequestInput0
func (t NavigateRequest_Input) AsNavigateRequestInput0() (NavigateRequestInput0, error) {
	var body NavigateRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNavigateRequestInput0 overwrites any union data inside the NavigateRequest_Input as the provided NavigateRequestInput0
func (t *NavigateRequest_Input) FromNavigateRequestInput0(v NavigateRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNavigateRequestInput0 performs a merge with any union data inside the NavigateRequest_Input, using the provided NavigateRequestInput0
func (t *NavigateRequest_Input) MergeNavigateRequestInput0(v NavigateRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsToolResult returns the union data inside the NavigateRequest_Input as a ToolResult
func (t NavigateRequest_Input) AsToolResult() (ToolResult, error) {
	var body ToolResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromToolResult overwrites any union data inside the NavigateRequest_Input as the provided ToolResult
func (t *NavigateRequest_Input) FromToolResult(v ToolResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeToolResult performs a merge with any union data inside the NavigateRequest_Input, using the provided ToolResult
func (t *NavigateRequest_Input) MergeToolResult(v ToolResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NavigateRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *NavigateRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Subscribe to server-sent events for graph changes
	// (GET /events)
	SubscribeEvents(w http.ResponseWriter, r *http.Request, params SubscribeEventsParams)
	// Introspect the full state machine graph
	// (GET /graph)
	GetGraph(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Server metadata and version information
	// (GET /info)
	GetInfo(w http.ResponseWriter, r *http.Request)
	// Transition to the next state based on input
	// (POST /navigate)
	Navigate(w http.ResponseWriter, r *http.Request)
	// Get the current view (actions) for a given state
	// (POST /render)
	Render(w http.ResponseWriter, r *http.Request)
	// Send a global signal to the state machine
	// (POST /signal)
	Signal(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Subscribe to server-sent events for graph changes
// (GET /events)
func (_ Unimplemented) SubscribeEvents(w http.ResponseWriter, r *http.Request, params SubscribeEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Introspect the full state machine graph
// (GET /graph)
func (_ Unimplemented) GetGraph(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Server metadata and version information
// (GET /info)
func (_ Unimplemented) GetInfo(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Transition to the next state based on input
// (POST /navigate)
func (_ Unimplemented) Navigate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the current view (actions) for a given state
// (POST /render)
func (_ Unimplemented) Render(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send a global signal to the state machine
// (POST /signal)
func (_ Unimplemented) Signal(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// SubscribeEvents operation middleware
func (siw *ServerInterfaceWrapper) SubscribeEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SubscribeEventsParams

	// ------------- Optional query parameter "session_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "session_id", r.URL.Query(), &params.SessionId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	// ------------- Optional query parameter "watch" -------------

	err = runtime.BindQueryParameter("form", true, false, "watch", r.URL.Query(), &params.Watch)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "watch", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubscribeEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGraph operation middleware
func (siw *ServerInterfaceWrapper) GetGraph(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGraph(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInfo operation middleware
func (siw *ServerInterfaceWrapper) GetInfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Navigate operation middleware
func (siw *ServerInterfaceWrapper) Navigate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Navigate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Render operation middleware
func (siw *ServerInterfaceWrapper) Render(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Render(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Signal operation middleware
func (siw *ServerInterfaceWrapper) Signal(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Signal(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events", wrapper.SubscribeEvents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/graph", wrapper.GetGraph)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/info", wrapper.GetInfo)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/navigate", wrapper.Navigate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/render", wrapper.Render)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/signal", wrapper.Signal)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xX3W7bOBN9FYLfd5EAiu1tu0Dhu24TtMZ2026cXjVBQEtjiy1FquTIiRH43RczlGxL",
	"lt1t0wV65R8OyZlzZg5nHmXqitJZsBjk+FGGNIdC8ddXKWpnr+BrBQHpj9K7Ejxq4OVSrYxTGX3NIKRe",
	"l2Qux/J8ZVWhU1EbiAxKsJm2C+GswByE4oMFrkoYyETayhg1MyDH6CtYJ5IW9o+9zoG3CDdvTjiBwWKQ",
	"iKuLy/OLq7vX7y+vLy6v6fffHy+m13eTyw8fr0/piniiDOi1Xcj1OpEevlbaQybHn+Lq7cbKzT5DinKd",
	"yEu11AuFcBADbcsK+12tAnjB68J5gc4Z4SFUBskfZ+H9XI4/PXY9Sx7l/z3M5Vj+b7glZlizMrx2zlzx",
	"KXJ9u05kQIUM1bFNUzbqBh239kV9BTYDfwWhdDbAftAR/Bg/QhG+dX87jzb8SuW9WsnvjCKRCL7QVpke",
	"2H0FQs85x9LKe7AorMtA5CoI64SrcOEoD9ErGzRHsZMdM+cMKMtI7YEybXw8iEXbl3c64DZTg0AnZiBK",
	"8HPnC8ia1PWMtUidRbDIufpzMK3jv6P473TWn6M6A4t6rsGTq01pLoFR66mbROY6oPOrPuxVyqW51EEj",
	"ZHxEaMWzd1jX5wKK+myVZUyPMh924CZ5SDr3/gmrs6UyFQhyDMTceREgBJKHpfKahGWX5C2jtVUNzr5z",
	"Mc0QerCb2EynCiE02QYPkFYsSZRqHlSaQyaUCNp+EZzeB/JstyK7lPXV5o4A7OUieO98byx9/L923nOJ",
	"Z5ycFAUd/loZIybnveTrcNe9YxMLhdK4tZ9orkIWwogWi+EGsp4noANMLxZkpO3c7V/46sOE00BbBE8J",
	"bRfiXmMeY/RgjA6C61n8pdJcWxAXdkEf2hJntGIgBFEoa8EPbiyBoZHck639bDUFvwQvE7kEH6IHo8Gz",
	"wYgwcSVYVWo5ls8Ho8FzmchSYc5sDWHZvLkLYNiIS0UxTDI5ltNqRkHN4CLa0VavCkDwgV+OdtDTOucn",
	"58RmaDbTDy4JDrcqM8paKkra87UCvyL0VcFEbwsiqfuAnmyiJ6qbSUWhzgKQf1T5ppa+uQYTk+teYZpH",
	"yRM3ksXuAZNaS27k6QGHeNtRX2457fidYiSfjUb0Ucsp74AHjFCfBfSgim2TwzXzoIqSic0UqrHwQC3L",
	"jY2cd25bd8WHqRHxXAEB1czokEPGpR2qolAkZ1sqmRpOl7NAO2MKMEELr8pcpLmyCwi8f8h/HcyPN4Bv",
	"2OCbEKiyNCRX2tnh50CO7yKwkedjmrunQ23p3keGin5eGVPHlcFcWz69A83EonehhBS5OnlLzNWiLs2I",
	"AgOSgzJ4FJG30eKJkLRlldypQjtZ3JfeprJHorpVSuQLHYQyegkdMN7pJViSlNK7WVwcNhJ3KOIJrf/U",
	"eFWp7zZSthv0aPDbYNT3LqiybFtiFMmzHLHs23Dg+OeskD8OawGoqIy75ddeFcpmovZAELy+UJvMHNq6",
	"5WdcXOgBvRkKZHykIOAfLlt9F+DHOrvuzLFuv4b1iPQkvo9d32n+e8C+hPtYosTki3h1tz1aKqOzOP2Q",
	"1e/9VgjeKlMrooitRZu6602j3vQoFh6wVoiZCpAJJpHvIfpiP32YvBjef0RdM2j9YoRNqzSFEOaVqceN",
	"ugqPchchfjqDbwBb89hSw704qaeiU376lFiQ8DVJRTQGvagnvH4ap3H9x2nsSPzmuv1XjHqRpnGNds3s",
	"diO5w/RViTeSfqIuwFUYG5o90XvyrJ40fvY3w7+kRoiT7awN2em/l4wXoxf7VpF2YR2KXNnM0Bxt3c44",
	"f/qkXJ2CpaFtYdyMDONlte60mpIYcjyprxl/51JlxDkst8NB5Y0cS3oQx8OhofXcBRw/ls7jmoaHZlaN",
	"Se/rQWqueKaSL0cv6entffbYet3XmNc199YFFCdXYBQN96cbb4Zyfbv+JwAA//8EOWjxARQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
